name: Debug ALB
on:
  workflow_dispatch:
    inputs:
      Runner_Id:
        type: string
        description: "Run ID from infra apply"
        required: true

permissions:
  id-token: write
  contents: read
  actions: read

env:
  TF_WORKING_DIR: Terraform/module
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: infra-prod-tf
          path: ${{ env.TF_WORKING_DIR }}
          run-id: ${{ inputs.Runner_Id }}
          github-token: ${{ github.token }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
    
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: 1.14.4
      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Get outputs
        id: out
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "CLUSTER_NAME=$(terraform output -raw eks_cluster_name)" >> "$GITHUB_OUTPUT"

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region "${{ env.AWS_REGION }}" --name "${{ steps.out.outputs.CLUSTER_NAME }}"

      # ========== ГЛАВНОЕ ==========

      - name: Show ingress
        run: kubectl get ingress -A
      - name: Info endpoints
        run: | 
          kubectl -n default get endpoints backend-service -o wide
          kubectl -n default describe endpoints backend-service
      - name: Pod status
        run: | 
          kubectl -n default get pods -l app=backend -o wide
          kubectl -n default describe pod -l app=backend

      - name: Describe ingress backend
        run: kubectl describe ingress backend -n default

      - name: ALB controller logs
        run: kubectl logs -n kube-system deployment/aws-load-balancer-controller | tail -n 200

      - name: Show services
        run: kubectl get svc -n default -o wide