name: Alb dns install
on: 
    workflow_dispatch:

permissions:
    id-token: write
    contents: read
    actions: read

env:
    TF_WORKING_DIR: Terraform/prod

jobs:
    dns:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Terraform setup
              uses: hashicorp/setup-terraform@v3
              with:
                version-terraform: 1.14.4

            - name: Aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE }}
                aws-region: ${{ secrets.AWS_REGION }}
            - name: Terraform init
              working-directory: ${{ env.TF_WORKING_DIR }}
              run: terraform init

            - name: Terraform apply
              working-directory: ${{ env.TF_WORKING_DIR }}
              run: terraform apply -auto-approve

