name: Terraform ECR Apply
on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read
jobs:
    terraform-aply:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Terraform install
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.14.4

            - name: Aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::336670698191:role/github-terraform-role
                aws-region: us-east-1
            
            - name: Terraform init
              working-directory: Terraform/module/stage/ecr-test
              run: terraform init
            - name: Terraform apply
              working-directory: Terraform/module/stage/ecr-test
              run: terraform apply -auto-approve
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: ecr-tfstate
                path: Terraform/module/stage/ecr-test/terraform.tfstate


