name: Terraform rds destroy
on:
    workflow_dispatch:
        inputs:
            Runner_id:
                type: string
                description: "Enter runner Id"
                required: true


permissions:
    id-token: write
    contents: read
    actions: read

jobs:
    terraform-rds-destroy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Terraform setup
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.14.4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: rds-tfstate
                path: Terraform/module/stage/rds-test
                run-id: ${{ inputs.Runner_id }}
                github-token: ${{ github.token }}
            - name: AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::336670698191:role/github-terraform-role
                aws-region: us-east-1
            - name: Terraform rds init
              working-directory: Terraform/module/stage/rds-test
              run: terraform init
            - name: Terraform destroy
              working-directory: Terraform/module/stage/rds-test
              run: terraform destroy -auto-approve