name: Terraform iam role apply
on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    iam-apply:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.14.4
            - name: Configure Aws Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
            - name: Terraform init
              working-directory: Terraform/module/stage/iam-policy-test
              run: terraform init
            - name: Terraform apply
              working-directory: Terraform/module/stage/iam-policy-test
              run: terraform apply -auto-approve
            - name: upload State
              uses: actions/upload-artifact@v4
              with:
                name: iam-tfstate
                path: Terraform/module/stage/iam-policy-test/terraform.tfstate
